services:
  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERBOSITY=-vv
    volumes:
      - ./config:/config
      # - ./scripts/fix-iptables-service.sh:/etc/services.d/fix-iptables/run:ro
      # - /var/log/auth.log:/var/log/auth.log:ro
      - ../logs/:/config/log/:rw
      - ../logs/nginx/:/remotelogs/nginx/:ro
    restart: unless-stopped
