services:
  ### Keycloak #########################################
  keycloak:
    container_name: "${APP_NAME}-keycloak"
    hostname: keycloak
    networks:
      backend:
        aliases:
          - keycloak
    image: quay.io/keycloak/keycloak:26.1
    restart: unless-stopped
    command: >
      start
      --db postgres
      --db-url-host postgres-kc
      --db-username keycloak
      --db-password ${KEYCLOAK_DATABASE_PASSWORD}
      --hostname https://${KEYCLOAK_FRONTEND_URL}
      --proxy-headers xforwarded
      --http-enabled true
      --spi-login-protocol-openid-connect-suppress-logout-confirmation-screen=true
      --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true
      --features token-exchange,preview,docker,persistent-user-sessions
      --health-enabled true
      --metrics-enabled false
    environment:
      KC_PROXY_HEADERS: xforwarded
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'exec 3<>/dev/tcp/localhost/9000 && echo -e \"GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n\" >&3 && timeout 5 cat <&3 | grep -q UP'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    depends_on:
      postgres-kc:
        condition: service_healthy
#    ports:
#      - "8080:8080"
#      - "8443:8443"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./themes/:/opt/keycloak/themes/
