networks:
  backend:
    driver: bridge

services:
  ### Cloudflare Tunnel ##################################
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
        - proxy
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
