services:
  ### Proxy #########################################
  proxy:
    image: nginx
    container_name: "${APP_NAME}-proxy"
    hostname: proxy
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./sites/:/etc/nginx/conf.d/
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificates:/etc/certificates/
      - ../shares/:/etc/shares
      - ../logs/nginx/:/var/log/nginx/
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    networks:
      - backend
      - frontend
    depends_on:
      keycloak:
        condition: service_healthy
      website:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
      pgadmin:
        condition: service_started
      phpmyadmin:
        condition: service_started
      portainer:
        condition: service_started
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
