#!/bin/bash
# infra/nomercy-stack/scripts/provision-security.sh
#
# Keeps the host's admin access and edge rules in the state this repo expects.
# nomercy-tv's deploy job runs it on every deploy, before the website deploy.
#
# 1. Admin allowlist. Every address in ADMIN_IPS skips UFW's SSH rate limit
#    and every fail2ban jail, and loses any ban it already has. The
#    nginx-direct-access jail bans an IP on ALL ports, forever, after one
#    request that skipped Cloudflare, so a single curl to the bare IP from
#    home locks the admins out of SSH. ADMIN_IPS comes from the deploy's
#    PRODUCTION_ADMIN_IPS secret and is never committed: this repo is public.
#    The same list lets admins into pgadmin/phpmyadmin/portainer
#    (write-admin-allow.sh); everyone else gets 403 there.
# 2. Removes the old UFW allows for the Docker API ports (2375/2376). Nothing
#    listens there; the rules would expose an unauthenticated root API the
#    moment a daemon config change bound it.
# 3. Tests and reloads nginx, so a proxy/sites change pulled by the deploy
#    takes effect even when the website deploy itself fails.
# 4. Cloudflare only on 80/443. Docker publishes the proxy's ports through
#    the FORWARD chain, which UFW's own rules never see, so anyone who knew
#    the origin IP could skip Cloudflare. A marked block in UFW's
#    after.rules (kept across reboots) filters new connections to 80/443 in
#    DOCKER-USER: Cloudflare's ranges (cloudflare-ips-v4.txt) and Docker's
#    own networks pass, everything else drops. The script then loads the
#    site through Cloudflare and takes the block out again if that fails.
#
# Idempotent: safe to re-run. An empty ADMIN_IPS leaves the allowlist as is.
#
# Run on the target host as root:
#   ADMIN_IPS="203.0.113.7 198.51.100.0/24" /opt/nomercy-stack/scripts/provision-security.sh

set -euo pipefail

STACK_DIR="/opt/nomercy-stack"
IGNORE_FILE="$STACK_DIR/fail2ban/config/fail2ban/jail.d/01-admin-ignoreip.local"
FAIL2BAN_CONTAINER="fail2ban"
PROXY_CONTAINER="${APP_NAME:-nomercy.tv}-proxy"
ADMIN_COMMENT="nomercy-admin"
CLOUDFLARE_IPS="$STACK_DIR/scripts/cloudflare-ips-v4.txt"
UFW_AFTER_RULES="/etc/ufw/after.rules"
BLOCK_BEGIN="# BEGIN nomercy-cloudflare-only (scripts/provision-security.sh)"
BLOCK_END="# END nomercy-cloudflare-only"
# Every Docker network on the host sits in this range. Containers calling out
# on 443 (TMDB, Cloudflare's API) pass DOCKER-USER too and must not drop.
DOCKER_NETWORKS="172.16.0.0/12"
VERIFY_URL="${VERIFY_URL:-https://nomercy.tv/}"

if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: must run as root" >&2
    exit 1
fi

admin_ips="$(echo "${ADMIN_IPS:-}" | tr ',' ' ' | xargs)"
for ip in $admin_ips; do
    if ! [[ "$ip" =~ ^[0-9A-Fa-f:.]+(/[0-9]{1,3})?$ ]]; then
        echo "ERROR: '$ip' in ADMIN_IPS is not an IP address or CIDR range" >&2
        exit 1
    fi
done

ufw_active=false
if command -v ufw >/dev/null && ufw status | grep -q "^Status: active"; then
    ufw_active=true
fi

# 1. Admin allowlist
if [ -z "$admin_ips" ]; then
    echo "WARN: ADMIN_IPS is empty; admin allowlist left as is"
else
    if $ufw_active; then
        # Drop allowlist rules for addresses no longer listed (a DHCP change).
        ufw status | { grep "# $ADMIN_COMMENT" || true; } \
            | awk '{ for (i = 1; i < NF; i++) if ($i == "ALLOW") { print $(i + 1); break } }' \
            | sort -u | while read -r old; do
                if ! [[ " $admin_ips " == *" $old "* ]]; then
                    ufw --force delete allow from "$old" to any port 22 proto tcp
                fi
            done
        # prepend puts the allow above the 22/tcp LIMIT rule, so it wins.
        for ip in $admin_ips; do
            ufw prepend allow from "$ip" to any port 22 proto tcp comment "$ADMIN_COMMENT"
        done
    fi

    cat > "$IGNORE_FILE" <<EOF
# Generated by scripts/provision-security.sh from the deploy's ADMIN_IPS.
# Gitignored because the repo is public. Do not edit by hand.
[DEFAULT]
ignoreip = 127.0.0.1/8 ::1 $admin_ips
EOF

    if docker ps --format '{{.Names}}' | grep -qx "$FAIL2BAN_CONTAINER"; then
        docker exec "$FAIL2BAN_CONTAINER" fail2ban-client reload
        for ip in $admin_ips; do
            docker exec "$FAIL2BAN_CONTAINER" fail2ban-client unban "$ip" || true
        done
    else
        echo "WARN: $FAIL2BAN_CONTAINER is not running; ignore list applies on its next start"
    fi
fi

# 2. Old Docker API allows
if $ufw_active; then
    for port in 2375 2376; do
        ufw --force delete allow "$port/tcp" >/dev/null 2>&1 || true
    done
fi

# 3. nginx
ADMIN_IPS="$admin_ips" bash "$STACK_DIR/scripts/write-admin-allow.sh"
docker exec "$PROXY_CONTAINER" nginx -t
docker exec "$PROXY_CONTAINER" nginx -s reload

# 4. Cloudflare only on 80/443
remove_block() {
    sed -i "\|^$BLOCK_BEGIN\$|,\|^$BLOCK_END\$|d" "$UFW_AFTER_RULES"
    # ufw reload never clears chains it did not create, so drop the live
    # rules by hand or the DROP stays in force until the next reboot.
    for port in 80 443; do
        while iptables -D DOCKER-USER -p tcp -m conntrack --ctorigdstport "$port" \
            --ctdir ORIGINAL -j nomercy-cloudflare 2>/dev/null; do :; done
    done
    iptables -F nomercy-cloudflare 2>/dev/null || true
    iptables -X nomercy-cloudflare 2>/dev/null || true
}

if $ufw_active; then
    ranges="$(grep -E '^[0-9]{1,3}(\.[0-9]{1,3}){3}/[0-9]{1,2}$' "$CLOUDFLARE_IPS" || true)"
    if [ "$(echo "$ranges" | grep -c .)" -lt 10 ]; then
        echo "ERROR: $CLOUDFLARE_IPS holds fewer than 10 ranges; refusing to lock 80/443 to it" >&2
        exit 1
    fi

    [ -f "$UFW_AFTER_RULES.nomercy-orig" ] || cp -p "$UFW_AFTER_RULES" "$UFW_AFTER_RULES.nomercy-orig"
    remove_block
    {
        echo "$BLOCK_BEGIN"
        echo "*filter"
        echo ":DOCKER-USER - [0:0]"
        echo ":nomercy-cloudflare - [0:0]"
        for port in 80 443; do
            echo "-A DOCKER-USER -p tcp -m conntrack --ctorigdstport $port --ctdir ORIGINAL -j nomercy-cloudflare"
        done
        echo "-A DOCKER-USER -j RETURN"
        for range in $DOCKER_NETWORKS $ranges; do
            echo "-A nomercy-cloudflare -s $range -j RETURN"
        done
        echo "-A nomercy-cloudflare -j DROP"
        echo "COMMIT"
        echo "$BLOCK_END"
    } >> "$UFW_AFTER_RULES"
    ufw reload

    code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 20 "$VERIFY_URL" || true)"
    if ! [[ "$code" =~ ^[23] ]]; then
        echo "ERROR: $VERIFY_URL answered $code with Cloudflare-only on; taking the block out" >&2
        remove_block
        ufw reload
        exit 1
    fi
    echo "OK: Cloudflare-only on 80/443; $VERIFY_URL answered $code"
fi

if $ufw_active; then
    ufw status numbered
    iptables -S DOCKER-USER
fi
