#!/bin/bash
# infra/nomercy-stack/scripts/provision-security.sh
#
# Keeps the host's admin access and edge rules in the state this repo expects.
# nomercy-tv's deploy job runs it on every deploy, before the website deploy.
#
# 1. Admin allowlist. Every address in ADMIN_IPS skips UFW's SSH rate limit
#    and every fail2ban jail, and loses any ban it already has. The
#    nginx-direct-access jail bans an IP on ALL ports, forever, after one
#    request that skipped Cloudflare, so a single curl to the bare IP from
#    home locks the admins out of SSH. ADMIN_IPS comes from the deploy's
#    PRODUCTION_ADMIN_IPS secret and is never committed: this repo is public.
# 2. Removes the old UFW allows for the Docker API ports (2375/2376). Nothing
#    listens there; the rules would expose an unauthenticated root API the
#    moment a daemon config change bound it.
# 3. Tests and reloads nginx, so a proxy/sites change pulled by the deploy
#    takes effect even when the website deploy itself fails.
#
# Idempotent: safe to re-run. An empty ADMIN_IPS leaves the allowlist as is.
#
# Run on the target host as root:
#   ADMIN_IPS="203.0.113.7 198.51.100.0/24" /opt/nomercy-stack/scripts/provision-security.sh

set -euo pipefail

STACK_DIR="/opt/nomercy-stack"
IGNORE_FILE="$STACK_DIR/fail2ban/config/fail2ban/jail.d/01-admin-ignoreip.local"
FAIL2BAN_CONTAINER="fail2ban"
PROXY_CONTAINER="${APP_NAME:-nomercy.tv}-proxy"
ADMIN_COMMENT="nomercy-admin"

if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: must run as root" >&2
    exit 1
fi

admin_ips="$(echo "${ADMIN_IPS:-}" | tr ',' ' ' | xargs)"
for ip in $admin_ips; do
    if ! [[ "$ip" =~ ^[0-9A-Fa-f:.]+(/[0-9]{1,3})?$ ]]; then
        echo "ERROR: '$ip' in ADMIN_IPS is not an IP address or CIDR range" >&2
        exit 1
    fi
done

ufw_active=false
if command -v ufw >/dev/null && ufw status | grep -q "^Status: active"; then
    ufw_active=true
fi

# 1. Admin allowlist
if [ -z "$admin_ips" ]; then
    echo "WARN: ADMIN_IPS is empty; admin allowlist left as is"
else
    if $ufw_active; then
        # Drop allowlist rules for addresses no longer listed (a DHCP change).
        ufw status | { grep "# $ADMIN_COMMENT" || true; } \
            | awk '{ for (i = 1; i < NF; i++) if ($i == "ALLOW") { print $(i + 1); break } }' \
            | sort -u | while read -r old; do
                if ! [[ " $admin_ips " == *" $old "* ]]; then
                    ufw --force delete allow from "$old" to any port 22 proto tcp
                fi
            done
        # prepend puts the allow above the 22/tcp LIMIT rule, so it wins.
        for ip in $admin_ips; do
            ufw prepend allow from "$ip" to any port 22 proto tcp comment "$ADMIN_COMMENT"
        done
    fi

    cat > "$IGNORE_FILE" <<EOF
# Generated by scripts/provision-security.sh from the deploy's ADMIN_IPS.
# Gitignored because the repo is public. Do not edit by hand.
[DEFAULT]
ignoreip = 127.0.0.1/8 ::1 $admin_ips
EOF

    if docker ps --format '{{.Names}}' | grep -qx "$FAIL2BAN_CONTAINER"; then
        docker exec "$FAIL2BAN_CONTAINER" fail2ban-client reload
        for ip in $admin_ips; do
            docker exec "$FAIL2BAN_CONTAINER" fail2ban-client unban "$ip" || true
        done
    else
        echo "WARN: $FAIL2BAN_CONTAINER is not running; ignore list applies on its next start"
    fi
fi

# 2. Old Docker API allows
if $ufw_active; then
    for port in 2375 2376; do
        ufw --force delete allow "$port/tcp" >/dev/null 2>&1 || true
    done
fi

# 3. nginx
docker exec "$PROXY_CONTAINER" nginx -t
docker exec "$PROXY_CONTAINER" nginx -s reload

if $ufw_active; then
    ufw status numbered
fi
