#!/bin/bash
# infra/nomercy-stack/scripts/write-admin-allow.sh
#
# Writes proxy/sites/admin-allow.inc: one `allow <ip>;` line per address in
# ADMIN_IPS. The admin sites (pgadmin, phpmyadmin, portainer) include it and
# then `deny all;`, so only admins reach them; without the file everyone gets
# 403. The file is gitignored because this repo is public.
#
# ADMIN_IPS comes from the environment, else from the stack's .env. On the
# droplet provision-security.sh calls this with the deploy's secret; on the
# dev box run it by hand after setting ADMIN_IPS in .env. Reload nginx after.
#   ./scripts/write-admin-allow.sh

set -euo pipefail

STACK_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ALLOW_FILE="$STACK_DIR/proxy/sites/admin-allow.inc"

if [ -z "${ADMIN_IPS:-}" ] && [ -f "$STACK_DIR/.env" ]; then
    ADMIN_IPS="$(sed -n 's/^ADMIN_IPS=//p' "$STACK_DIR/.env" | tail -1 | tr -d '"'"'"'\r')"
fi

admin_ips="$(echo "${ADMIN_IPS:-}" | tr ',' ' ' | xargs)"
if [ -z "$admin_ips" ]; then
    echo "WARN: ADMIN_IPS is empty; $ALLOW_FILE left as is (no file = admin sites answer 403)"
    exit 0
fi

{
    echo "# Generated by scripts/write-admin-allow.sh from ADMIN_IPS. Do not edit."
    for ip in $admin_ips; do
        if ! [[ "$ip" =~ ^[0-9A-Fa-f:.]+(/[0-9]{1,3})?$ ]]; then
            echo "ERROR: '$ip' in ADMIN_IPS is not an IP address or CIDR range" >&2
            exit 1
        fi
        echo "allow $ip;"
    done
} > "$ALLOW_FILE.tmp"
mv "$ALLOW_FILE.tmp" "$ALLOW_FILE"
echo "OK: $ALLOW_FILE allows $admin_ips"
