[nginx-zero-tolerance]
enabled = true
filter = nginx-zero-tolerance
logpath = /remotelogs/nginx/access.log
maxretry = 1
findtime = 86400
bantime = -1
action = iptables-allports[name=nginx-zero-tolerance]
