[nginx-vuln-scan]
enabled = true
port = http,https
filter = nginx-vuln-scan
logpath = /remotelogs/nginx/access.log
maxretry = 5
bantime = 86400  # 24 hours
findtime = 600   # 10 minutes
backend = auto
