[nginx-aggressive-scan]
enabled = true
filter = nginx-aggressive-scan
logpath = /remotelogs/nginx/access.log
maxretry = 1
findtime = 86400
bantime = -1
action = iptables-allports[name=nginx-aggressive-scan]
