FROM alpine:3.22.2
LABEL Maintainer="Stoney Eagle <stoney@nomercy.tv>"
LABEL Description="Lightweight container with Nginx 1.26 & PHP 8.4 based on Alpine Linux. DEV build."

# Setup document root
WORKDIR /var/www/html

RUN adduser -D -g '' www sudo

# Install packages and remove default server definition
RUN apk add --no-cache \
  curl \
  nginx \
  php84 \
  php84-bcmath \
  php84-ctype \
  php84-curl \
  php84-dom \
  php84-fileinfo \
  php84-fpm \
  php84-ftp \
  php84-gd \
  php84-iconv \
  php84-intl \
  php84-mbstring \
  php84-mysqli \
  php84-opcache \
  php84-openssl \
  php84-pdo_mysql \
  php84-pdo_sqlite \
  php84-pdo_pgsql \
  php84-phar \
  php84-session \
  php84-simplexml \
  php84-sqlite3 \
  php84-tokenizer \
  php84-sodium \
  php84-xml \
  php84-xmlreader \
  php84-xmlwriter \
  php84-zip \
  bash \
  curl \
  git \
  htop \
  imagemagick \
  libcurl \
  libwebp-dev \
  libzip-dev \
  nano \
  npm \
  openjpeg \
  openssh-client \
  patch \
  supervisor \
  texinfo \
  wget \
  yarn \
  zlib

RUN ln -s /usr/bin/php84 /usr/bin/php

# Configure nginx - http
COPY infra/nomercy-stack/website/config/nginx.conf /etc/nginx/nginx.conf
# Configure nginx - default server
COPY infra/nomercy-stack/website/config/conf.d /etc/nginx/conf.d/

# Configure PHP-FPM
ENV PHP_INI_DIR /etc/php84
ENV php_ini ${PHP_INI_DIR}/php.ini
ENV fpm_conf ${PHP_INI_DIR}/php-fpm.d/www.conf

COPY infra/nomercy-stack/website/config/fpm-pool.conf ${fpm_conf}
COPY infra/nomercy-stack/website/config/php.ini ${php_ini}

# Configure supervisord
COPY infra/nomercy-stack/website/config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Make sure files/folders needed by the processes are accessable when they run under the www user
RUN chown -R www:www /var/www/html /run /var/lib/nginx /var/log/nginx

# Install composer
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

# Copy application code and install dependencies at build time
COPY --chown=www apps/nomercy-tv/ /var/www/html/
RUN su -s /bin/bash www -c "composer install --working-dir=/var/www/html --no-interaction --optimize-autoloader"
RUN su -s /bin/bash www -c "cd /var/www/html && yarn && yarn build"

# Stash pre-built deps outside the volume mount point
RUN cp -a /var/www/html/vendor /opt/_vendor_built \
 && cp -a /var/www/html/node_modules /opt/_node_modules_built

# Expose the port nginx is reachable on
ADD infra/nomercy-stack/website/config/start.sh /start.sh
RUN chmod 755 /start.sh

ADD infra/nomercy-stack/website/config/resolv.conf /etc/resolv.conf

EXPOSE 8080

RUN sed -i -e 's/\r$//' /start.sh

CMD ["/start.sh"]

# Configure a healthcheck to validate that everything is up&running
HEALTHCHECK --timeout=10s CMD curl --silent --fail http://127.0.0.1:8080/fpm-ping || exit 1
