
# laravel dev hot reload
server {
    listen [::]:443 ssl;
    listen 443 ssl;
    ssl_certificate /etc/certificates/cert.pem;
    ssl_certificate_key /etc/certificates/key.pem;

    server_name api-dev.nomercy.tv cdn-dev.nomercy.tv docs-dev.nomercy.tv dev.nomercy.tv;

    add_header Cache-Control "max-age=31536000";

    large_client_header_buffers 4 4092k;
    client_max_body_size 1000M;

    location / {

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;

        proxy_read_timeout 300;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_pass http://website:8080;
    }

    location /laravel-vite/ {
      # WebSocket support
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

      proxy_pass  http://192.168.2.201:5173/laravel-vite/;

    }

    location /vendor/ {
      # WebSocket support
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

      proxy_pass  http://192.168.2.201:5173/vendor/;
#       proxy_pass http://website:80/vendor/;
    }

    location /vendor/nova/ {
      # WebSocket support
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

      proxy_pass http://website:8080/vendor/nova/;
    }

    location /@id/ {
      # WebSocket support
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

      proxy_pass  http://192.168.2.201:5173/@id/;
    }

    location /resources/foiee/ {
      # WebSocket support
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

      proxy_pass http://keycloak:8080/resources/foiee/;
    }

    location /resources/ {
      # WebSocket support
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

      proxy_pass  http://192.168.2.201:5173/resources/;
    }

    location /node_modules/ {
      # WebSocket support
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

      proxy_pass  http://192.168.2.201:5173/node_modules/;
    }

    location /@vite/ {
      # WebSocket support
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

      proxy_pass  http://192.168.2.201:5173/@vite/;
    }

}
