
# auth
server {
    listen [::]:443 ssl;
    listen 443 ssl;
    ssl_certificate /etc/certificates/cert.pem;
    ssl_certificate_key /etc/certificates/key.pem;

    server_name auth-dev.nomercy.tv auth.nomercy.tv;

    large_client_header_buffers 4 4092k;
    client_max_body_size 100M;

    location / {
        limit_req zone=auth_limit burst=20 nodelay;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;

        proxy_cookie_path ~^/(.+)$ "/$1; SameSite=none; Secure; ";

        # strip X-Frame-Options so CSP frame-ancestors (set in Keycloak admin) takes over
        proxy_hide_header X-Frame-Options;

        # accept origin header
        proxy_hide_header 'Access-Control-Allow-Origin';
        proxy_hide_header 'Access-Control-Allow-Headers';
        add_header 'Access-Control-Allow-Origin' "$http_origin" always;
        add_header 'Access-Control-Allow-Headers' '*' always;

        proxy_pass http://keycloak:8080;
    }

}
