
# portainer
server {
    listen [::]:443 ssl;
    listen 443 ssl;
    ssl_certificate /etc/certificates/cert.pem;
    ssl_certificate_key /etc/certificates/key.pem;

    server_name portainer.nomercy.tv portainer-dev.nomercy.tv;

    add_header Cache-Control "max-age=31536000";

    large_client_header_buffers 4 4092k;
    client_max_body_size 100M;

    location / {

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;

        proxy_buffer_size 10240k;
        proxy_buffers 128 10240k;
        proxy_busy_buffers_size 10240k;

        proxy_ssl_verify off;
        proxy_pass https://192.168.2.60:9443;
    }

}
